### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by krzysk1** [krzysk1/bocian#1]
dynamic model
- wheel below groud, wheel is bumpy on the ground DONE
- wings to join a bit stronger  DONE 

visual
- increase reflection on fuselage DONE
- turn indicator textured wrongly DONE
- reduce reflection on panel and its cover DONE
- reduce reflection on mic button DONE

operation
- lack of compass indication DONE
- lack of turn ball movement  DONE
- add altimeter pressure setting DONE
- add hook release animation and sounds - DONE
- lack of trim animation - DONE
- implement manual operation in controls.tmd - DONE
- set copilot.tmd  DONE

sounds
- remove strange sounds - DONE
- add opening airbrake sound - DONE

**Comment by Jetjockey10** [comment]
Aileron roll seems a bit heavy but, glides OK.  Very pretty glider.  Gauges could be sharper, more contrast.  Canopy could be clearer, for better visibility.  Enjoyed flying -9.  Thanks.

**Comment by krzysk1** [comment]
On that type of glider I made my first solo flights:)

**Comment by HerveF2** [comment]
I'm unable to fly it: once in the air, trim seems direct to pitch the nose low.... and without crash, suddenly the bocian is reinitialised in the rwy threshold of the nearest airport (Zweisimmen from Switzerland DLC). I've flown more than 600 hours in AFS2 and I've never seen such curious behaviour ! Try to put the Bocian around 5000 ft in the air over Zweisimmen, and see waht happens ?

Very fine and handsome classic glider:I like how the exterior looks (a bit "used"). But for me inside the cockpit all is way too shiny and bright.

Suggestions: identify the flight model problem, and optimise the sensitivity of the wings(once on the ground, when the wings pitch gently left or right, like any glider, the wing broke.

suggestion: reduce the shiny and bright inner texture. DONE

**Comment by krzysk1** [comment]
dynamic model changed. I didnot observe such behaviour any more
