### ISSUE TITLE
Bocian still unflyable

### ISSUE THREAD

**Issue by HerveF2** [krzysk1/bocian#2]
Hello, The Bocian is great looking, but still non flyable... After some seconds in the air, his nose goes down... not possible to trim up...and suddenly the plane returns on the nearest runway thershold...

I let you check, thx and greetings

**Comment by krzysk1** [comment]
Hmm, I cannot observe any unusual behaviour of this glider. 
Matt reports similiar issues but I don;t know the reason

**Comment by krzysk1** [comment]
And did you download the lastest update from github?

**Comment by HerveF2** [comment]
Yes, for sure !

I'm flying in Innsbruck and Switzerland.... perhaps is it linked with air
density, due of the height of these regions (as far as I know, air density
is simuilated in AFS2)


*Hervé Forclaz*
Bureau artistique / Booking & Management
Chemin des Amandiers 84
1950 SION (Suisse)
++41 (0)79 204 12 54
forclazherve@gmail.com

Représentation exclusive:
*Tango Sensations - Les Nuits de Bessarabie - Hervé Lenoir*
Représentation suisse :

*Michel Fugain & Pluribus - Orient Occident le Groupe*

www.tangosensations.ch
http://www.clenastein.com/The_Bessarabian_Nights.html
https://soundcloud.com/herve-lenoir
https://www.facebook.com/michel.fugain.fanpageofficielle/
https://www.facebook.com/orientoccidentlegroupe/

**Comment by krzysk1** [comment]
should be corrected (I cannot see such behaviuor)

**Comment by krzysk1** [comment]
solved!
