### ISSUE TITLE
Still unflyable 2 but a bit better

### ISSUE THREAD

**Issue by HerveF2** [krzysk1/bocian#4]
So sorry, but after 1 minute, both wings break in the air.... now what is better: wings don’t break anymore when the glider is static at ground.

But really, it is a pity. I cannot fly without breaking the wings after... 30 seconds or 60 seconds.... and if you try to apply spoilers, wings break as welll...

Greetings

**Comment by krzysk1** [comment]
I didn't notice such behaviour. What is your AFS2 version and OS?

I modified some settings (copied from Swift glider) - please try again. I hope it helps

**Comment by HerveF2** [comment]
Krzysk1, this time (since the commit « joint wings », all is solved !

The bocian works perfectly, and the spoiler brakes too, without breaking the wings.

Thank you very much ! 

Greetings from switzerland, herve

Envoyé de mon iPad
